### ISSUE TITLE
Use primitive strings instead of wrapped strings in Links response

### ISSUE THREAD

**Issue by kk-ds-000** [manybrain/mailinator-javascript-client#7]
The `links` property below uses an `Array<String>` type instead of an `Array<string>` type:

https://github.com/manybrain/mailinator-javascript-client/blob/324b4de056c7689b9b963393ba7fe0341696acb5/src/message/Links.ts#L1-L3

The use of wrapped `String` objects is [not recommended](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#number-string-boolean-symbol-and-object).

It also forces consumers that expect an array of string primitives to convert the wrapped objects to primitives via custom code or a type assertion.

**Comment by marianmelnychuk** [comment]
Thank you for your remark. I've fixed it
