### ISSUE TITLE
GetInboxRequest not returning parts

### ISSUE THREAD

**Issue by fissilejonathan** [manybrain/mailinator-javascript-client#8]
I have the following code returning a 200 but the parts property on the message is missing:

```
          const response: IRestResponse<Inbox> = await mailinatorClient.request(
            new GetInboxRequest(<domain>)
          );
```

**Comment by richard-jfc** [comment]
You need to make a `GetMessageRequest` to retrieve parts, they're not populated on the `GetInboxRequest`
